# Generated by Django 3.1.7 on 2023-02-10 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0113_auto_20230128_0944"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTokens",
            fields=[
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_id",
                    models.UUIDField(
                        default=uuid.UUID("76a9ff90-89dc-4803-bc8f-ef7c25768425"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret_key", models.CharField(max_length=25)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openapi_customtokens_created_by_user_id",
                        to="organization.organizationuser",
                    ),
                ),
                (
                    "deleted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openapi_customtokens_deleted_by_user_id",
                        to="organization.organizationuser",
                    ),
                ),
                (
                    "modified_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openapi_customtokens_modified_by_user_id",
                        to="organization.organizationuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organizationuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
