# Generated by Django 4.2.6 on 2023-11-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0171_itemtagvendorlinkage"),
        ("openapi", "0003_auto_20230411_0812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtokens",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by_user_id",
                to="organization.organizationuser",
            ),
        ),
        migrations.AlterField(
            model_name="customtokens",
            name="deleted_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_deleted_by_user_id",
                to="organization.organizationuser",
            ),
        ),
        migrations.AlterField(
            model_name="customtokens",
            name="modified_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_modified_by_user_id",
                to="organization.organizationuser",
            ),
        ),
    ]
