# Generated by Django 4.2.6 on 2026-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0005_bulkprojecttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('project', 'Project'), ('item', 'Item')], db_index=True, max_length=50)),
                ('enterprise_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('success', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BulkProjectTask',
        ),
        migrations.AddIndex(
            model_name='bulktask',
            index=models.Index(fields=['enterprise_id', 'task_id'], name='openapi_bul_enterpr_7b7102_idx'),
        ),
        migrations.AddIndex(
            model_name='bulktask',
            index=models.Index(fields=['enterprise_id', 'task_type'], name='openapi_bul_enterpr_2fc037_idx'),
        ),
    ]
