# Generated by Django 4.2.6 on 2026-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0006_bulktask_delete_bulkprojecttask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktask',
            name='task_type',
            field=models.CharField(choices=[('project', 'Project'), ('item', 'Item'), ('contract', 'Contract')], db_index=True, max_length=50),
        ),
    ]
