# Generated by Django 4.2.6 on 2026-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0007_alter_bulktask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktask',
            name='task_type',
            field=models.CharField(choices=[('project', 'Project'), ('item', 'Item'), ('contract', 'Contract'), ('purchase_order', 'Purchase Order')], db_index=True, max_length=50),
        ),
    ]
