# Generated by Django 3.1.7 on 2023-02-13 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtokens",
            name="entry_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
