# Generated by Django 3.1.7 on 2023-04-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0126_remove_entity_entity_logo"),
        ("openapi", "0002_auto_20230213_0610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtokens",
            name="user",
        ),
        migrations.AddField(
            model_name="customtokens",
            name="enterprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="customtokens",
            name="secret_key",
            field=models.UUIDField(),
        ),
    ]
