# Generated by Django 4.2.6 on 2026-01-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0004_alter_customtokens_created_by_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("enterprise_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("success", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("results", models.JSONField(default=list)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enterprise_id", "task_id"],
                        name="openapi_bul_enterpr_8e3bc8_idx",
                    )
                ],
            },
        ),
    ]
